[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = ["python3-dev", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt --no-cache-dir"]

[start]
cmd = "python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300"
